# Generated by Django 5.2 on 2025-04-23 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customuser_bio_customuser_experience_years_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
