# Generated by Django 5.2 on 2025-04-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_case_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='applicable_laws',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='case_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='case_status',
            field=models.CharField(blank=True, choices=[('fir_registered', 'FIR Registered'), ('under_investigation', 'Under Investigation'), ('challan_submitted', 'Challan Submitted'), ('trial_started', 'Trial Started'), ('appeal_filed', 'Appeal Filed'), ('settled', 'Settled')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='court_name',
            field=models.CharField(blank=True, choices=[('district', 'District Court'), ('high', 'High Court'), ('supreme', 'Supreme Court'), ('family', 'Family Court'), ('anti_terrorism', 'Anti-terrorism Court'), ('banking', 'Banking Court'), ('customs', 'Customs Court')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='case_documents/'),
        ),
        migrations.AddField(
            model_name='case',
            name='fir_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='hearing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='opposing_party',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='police_station',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
