# Generated by Django 5.2 on 2025-04-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_customuser_area_customuser_cases_handled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_complexity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=50),
        ),
        migrations.AddField(
            model_name='case',
            name='case_subtype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='case_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
